import React, { ReactNode, ReactElement } from 'react'
import Head from 'next/head'

interface DefaultLayoutProps {
  children: ReactNode
}
export default function DefaultLayout({ children }: DefaultLayoutProps): ReactElement {
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/logo_yumemi.svg" />
      </Head>
      {children}
    </div>
  )
}
